---
apiVersion: v1

kind: Namespace

metadata:
  name: usgs

spec: {}

---
apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: usgs-api
  name: usgs-api
  namespace: usgs

spec:
  replicas: 2
  selector:
    matchLabels:
      app: usgs-api
  template:
    metadata:
      labels:
        app: usgs-api
    spec:
      containers:
      - image: devansharma92/usgs-api-earthquake:v4.0
        name: usgs-api-earthquake
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/earthquake/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1

kind: Service

metadata:
  name: usgs-service
  namespace: usgs

spec:
  type: NodePort
  selector:
    app: usgs-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007

---
apiVersion: autoscaling/v2

kind: HorizontalPodAutoscaler

metadata:
  name: usgs-api-hpa
  namespace: usgs

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usgs-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75