---
apiVersion: v1

kind: Service

metadata:
  name: usgs-service
  namespace: usgs

spec:
  type: NodePort
  selector:
    app: usgs-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
